name: Test

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: '${{ matrix.os }}'
    name: 'Test: ${{ matrix.os }}'
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up WireGuard
        uses: ./
        with:
          endpoint: '${{ secrets.ENDPOINT }}'
          endpoint_public_key: '${{ secrets.ENDPOINT_PUBLIC }}'
          ips: '${{ secrets.IPS }}'
          allowed_ips: '${{ secrets.ALLOWED_IPS }}'
          private_key: '${{ secrets.PRIVATE }}'
          keepalive: 25
      - name: Check whoami
        run: |
          whoami
      - name: Check $HOME
        run: |
          echo $HOME
          ls -la $HOME    
      - name: Check github.action_path
        run: |
          echo ${{ github.action_path }}
          ls -la ${{ github.action_path }}
      - name: Check github.workspace
        run: |    
          echo ${{ github.workspace }} 
          ls -la ${{ github.workspace }}
      - name: Check runner.workspace
        run: |          
          echo ${{ runner.workspace }}
          ls -la ${{ runner.workspace }}
      - name: Check ping
        run: ping -W 10 -c 5 -- 192.168.0.228
      - name: Check endpoint version
        run: |
          ssh -V
          uname -a
          rsync --version
          git --version
      - name: create ssh config
        run: |
          mkdir -p $HOME/.ssh
          echo '${{ secrets.TOMARS }}'| sudo tee $HOME/.ssh/config
          cat $HOME/.ssh/config
      # - name: Check endpoint rpodstrigach
      #   uses: appleboy/ssh-action@v1.0.3
      #   with:
      #     host: ${{ secrets.HOST_IP }}
      #     username: rpodstrigach
      #     key: ${{ secrets.TOMARS }}
      #     script: |
      #       whoami
      #       ls -la
      #       ls -la $HOME
      #       #rsync -avh --delete --progress ${{ github.workspace }}/nginx.yaml ~

      # - name: Check endpoint MIR-SRV-CV-01
      #   uses: appleboy/ssh-action@v1.0.3
      #   with:
      #       host: 10.36.68.146
      #       username: nvidia
      #       key: ${{ secrets.TOMARS }}
      #       proxy_host: 192.168.0.228
      #       proxy_username: ct402130
      #       proxy_key: ${{ secrets.TOMARS }}
      #       script: |
      #         whoami
      #         ls -al

            # - name: Check endpoint echo 
      #   run: |          
      #     echo 'github.workspace === ${{ github.workspace }}'
      #     echo "GITHUB_WORKSPACE === $GITHUB_WORKSPACE"
      #     echo 'runner.workspace === ${{ runner.workspace }}'
      #     echo "RUNNER_WORKSPACE === $RUNNER_WORKSPACE"
              
