name: Test

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: '${{ matrix.os }}'
    name: 'Test: ${{ matrix.os }}'
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up WireGuard
        uses: ./
        with:
          endpoint: '${{ secrets.ENDPOINT }}'
          endpoint_public_key: '${{ secrets.ENDPOINT_PUBLIC }}'
          ips: '${{ secrets.IPS }}'
          allowed_ips: '${{ secrets.ALLOWED_IPS }}'
          private_key: '${{ secrets.PRIVATE }}'
          keepalive: 25
      - name: Check endpoint
        run: ping -W 10 -c 5 -- 192.168.0.228
      - name: Check endpoint rpodstrigach
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST_IP }}
          username: rpodstrigach
          key: ${{ secrets.TOMARS }}
          script: |
            #whoami
            #ls -la
            #rsync -avh --delete --progress ${{ github.workspace }}/nginx.yaml ~
            #ls -la
            echo ${{ github.workspace }}
            ls -la ${{ github.workspace }}
            ls -la ${{ runner.workspace }}
            echo 'github.workspace === ${{ github.workspace }}'
            echo "GITHUB_WORKSPACE === $GITHUB_WORKSPACE"
            echo 'runner.workspace === ${{ runner.workspace }}'
            echo "RUNNER_WORKSPACE === $RUNNER_WORKSPACE"
      # - name: Check endpoint MIR-SRV-CV-01
      #   uses: appleboy/ssh-action@v1.0.3
      #   with:
      #       host: 10.36.68.146
      #       username: nvidia
      #       key: ${{ secrets.TOMARS }}
      #       proxy_host: 192.168.0.228
      #       proxy_username: ct402130
      #       proxy_key: ${{ secrets.TOMARS }}
      #       script: |
      #         whoami
      #         ls -al
              
