name: Test

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: '${{ matrix.os }}'
    name: 'Test: ${{ matrix.os }}'
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install WireGuard
        run: |
          sudo DEBIAN_FRONTEND=noninteractive apt-get install -yq --no-install-recommends wireguard-tools
          sudo ls -la /etc/wireguard
          echo '${{ secrets.WG_MARS_GITHUB_CONFIG }}'| sudo tee /etc/wireguard/wg-client.conf
          sudo ls -la /etc/wireguard
          sudo systemctl start wg-quick@wg-client.service
          sudo wg
    #   - name: Set up WireGuard
    #     uses: ./
    #     with:
    #       endpoint: '${{ secrets.ENDPOINT }}'
    #       endpoint_public_key: '${{ secrets.ENDPOINT_PUBLIC }}'
    #       ips: '${{ secrets.IPS }}'
    #       allowed_ips: '${{ secrets.ALLOWED_IPS }}'
    #       private_key: '${{ secrets.PRIVATE }}'
    #       keepalive: 25
      - name: Check whoami
        run: |
          whoami
      - name: Check $HOME
        run: |
          echo $HOME
          ls -la $HOME    
      - name: Check github.action_path
        run: |
          echo ${{ github.action_path }}
          ls -la ${{ github.action_path }}
      - name: Check github.workspace
        run: |    
          echo ${{ github.workspace }} 
          ls -la ${{ github.workspace }}
      - name: Check runner.workspace
        run: |          
          echo ${{ runner.workspace }}
          ls -la ${{ runner.workspace }}
      - name: Check version
        run: |
          uname -a
          wg --version
          ssh -V
          rsync --version
          git --version      
      - name: Check ping
        run: ping -W 10 -c 5 -- 192.168.0.228
      - name: create ssh
        run: |
          mkdir -p $HOME/.ssh
          echo '${{ secrets.TOMARS }}'| sudo tee $HOME/.ssh/id_ed25519-open-to-github
          ls -la $HOME/.ssh/
      - name: create ssh config
        run: |
          echo '${{ secrets.SSH_CONFIG_MARS_LAPTOP_VKROTOV }}'| sudo tee $HOME/.ssh/config
      - name: Check ssh connect
        run: |
            ssh -v mars_laptop_vkrotov 'whoami && dir'
            ssh -v MIR-SRV-CV-01 'whoami && ls -la'
      - name: rsync
        run: |
            rsync -avh --delete --progress ${{ github.workspace }}/nginx.yaml MIR-SRV-CV-01:~
            ssh -v MIR-SRV-CV-01 'ls -la'
 
      
      # - name: Check endpoint rpodstrigach
      #   uses: appleboy/ssh-action@v1.0.3
      #   with:
      #     host: ${{ secrets.HOST_IP }}
      #     username: rpodstrigach
      #     key: ${{ secrets.TOMARS }}
      #     script: |
      #       whoami
      #       ls -la
      #       ls -la $HOME
      #       #rsync -avh --delete --progress ${{ github.workspace }}/nginx.yaml ~

      # - name: Check endpoint MIR-SRV-CV-01
      #   uses: appleboy/ssh-action@v1.0.3
      #   with:
      #       host: 10.36.68.146
      #       username: nvidia
      #       key: ${{ secrets.TOMARS }}
      #       proxy_host: 192.168.0.228
      #       proxy_username: ct402130
      #       proxy_key: ${{ secrets.TOMARS }}
      #       script: |
      #         whoami
      #         ls -al

              
